### ISSUE TITLE
Ability to change minifab colors

### ISSUE THREAD

**Issue by JustKhit** [iamageo/MultiFab#14]
Thanks for nice fab library. I've been using this on my project.

However, I wasn't able to change iconTint and backgroundTint of the minifab, and found that there is a fix colors on the MiniFabItem.

Here is a little update you might consider:

### MultiFloatingActionButton.kt
![Screenshot 2023-12-29 at 11 20 41 AM](https://github.com/iamageo/MultiFab/assets/126133522/70a0b91b-f4d3-45c5-b621-6fafc2ae34f1)

### MiniFabItem.kt
![Screenshot 2023-12-29 at 11 21 16 AM](https://github.com/iamageo/MultiFab/assets/126133522/ec2b6618-98f8-4e6a-997b-8ce44c5bab6a)

Thanks

**Comment by iamageo** [comment]
@JustKhit I'm very happy that the library is being useful, I will update it with your considerations, thank you very much for that.

For the next suggestions, I recommend that you open a **pull request** with the changes, this way the project is less independent of me and the community helps maintain it, big hug!

**Comment by iamageo** [comment]
I just created a new version [1.0.8](https://jitpack.io/#iamageo/MultiFab) taking into account the points you mentioned, I hope it is useful, I remain at your disposal. 
```
dependencies {
   implementation 'com.github.iamageo:MultiFab:1.0.8'
}
```
